name: esys_flutter_share
description: A Flutter plugin for sharing images & text with other applications.
version: 1.0.2
homepage: https://github.com/esysberlin/esys-flutter-share

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.0.9

flutter:
  plugin:
    androidPackage: de.esys.esysfluttershare
    pluginClass: EsysFlutterSharePlugin
